import React, { useState } from 'react'

function toWebp(src: string): string | null {
  if (!src.startsWith('/images/')) return null
  const match = src.match(/\.(jpe?g|png)$/i)
  if (!match) return null
  return src.slice(0, -match[0].length) + '.webp'
}

export interface OptimizedImageProps extends React.ImgHTMLAttributes<HTMLImageElement> {
  src: string
  alt: string
}

/**
 * Drop-in replacement for `<img>` that prefers a WebP sibling (generated by
 * `npm run optimize:images`). If that WebP fails to load, falls back to the
 * original jpg/png once. WebP files stay gitignored and generated at build.
 */
export const OptimizedImage: React.FC<OptimizedImageProps> = ({ src, alt, onError, ...imgProps }) => {
  const webpSrc = toWebp(src)
  const [failedWebp, setFailedWebp] = useState(false)
  const effectiveSrc = webpSrc && !failedWebp ? webpSrc : src

  return (
    <img
      src={effectiveSrc}
      alt={alt}
      {...imgProps}
      onError={(event) => {
        if (webpSrc && !failedWebp && effectiveSrc === webpSrc) {
          setFailedWebp(true)
          return
        }
        onError?.(event)
      }}
    />
  )
}
