import React from 'react'

function toWebp(src: string): string | null {
  if (!src.startsWith('/images/')) return null
  const match = src.match(/\.(jpe?g|png)$/i)
  if (!match) return null
  return src.slice(0, -match[0].length) + '.webp'
}

export interface OptimizedImageProps extends React.ImgHTMLAttributes<HTMLImageElement> {
  src: string
  alt: string
}

/**
 * Drop-in replacement for `<img>` that additionally offers a WebP source
 * (generated by `npm run optimize:images`, see scripts/optimize-images.ts)
 * to browsers that support it, falling back to the original JPG/PNG
 * otherwise. Meaningfully reduces transferred bytes on image-heavy pages
 * without touching any existing `src` paths in the data layer.
 */
export const OptimizedImage: React.FC<OptimizedImageProps> = ({ src, alt, ...imgProps }) => {
  const webpSrc = toWebp(src)

  if (!webpSrc) {
    return <img src={src} alt={alt} {...imgProps} />
  }

  return (
    <picture>
      <source srcSet={webpSrc} type="image/webp" />
      <img src={src} alt={alt} {...imgProps} />
    </picture>
  )
}
